# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-14 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import plugins.customstyling.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0046_auto_20210922_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossJournalStylesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stylesheet_name', models.CharField(default=plugins.customstyling.models.generate_stylesheet_name, max_length=40)),
                ('journals', models.ManyToManyField(to='journal.Journal')),
            ],
        ),
    ]
