# Generated by Django 4.2.22 on 2026-07-13 16:57

import core.model_utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_alter_account_preferred_timezone'),
        ('press', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='press_hero_image', to='core.file', verbose_name='Press Hero'),
        ),
        migrations.AddField(
            model_name='press',
            name='homepage_h1_text',
            field=models.CharField(blank=True, help_text='The H1 to display on the press homepage hero. Default is the press name if blank.', max_length=30, verbose_name='Homepage H1 Text'),
        ),
        migrations.AddField(
            model_name='press',
            name='homepage_slogan',
            field=core.model_utils.JanewayBleachField(blank=True, help_text='A slogan to show in the Janeway hero. Optional.', verbose_name='Homepage Slogan'),
        ),
    ]
