# Generated by Django 4.2.22 on 2026-07-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0036_remove_press_password_reset_text_and_more'),
        ('press', '0037_press_hero_image_press_homepage_h1_text_and_more'),
    ]

    operations = [
    ]
